### ISSUE TITLE
Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground() with HyperTrack SDK version: 0.1.9

### ISSUE THREAD

**Issue by bikcrum** [hypertrack/sdk-flutter#11]
I picked this error from crash analytics

#### Error:
```
Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{9d90309 u0 eu.chaincode.chaincargodriver/com.hypertrack.sdk.service.HyperTrackSDKService}
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2240)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

#### Device:
Brand:samsung
Model:Galaxy S10
Orientation: Portrait
RAM free: 2.55 GB
Disk free: 39.64 GB
Operating System
Version:11
Orientation: Portrait
Rooted:No

**Comment by deniszpua** [comment]
Hey @bikcrum.
We've refactored the code so since [v0.2.0](https://pub.dev/packages/hypertrack_plugin/versions/0.2.0) it shouldn't happen anymore.
The only reason you can see this, if your app is doing too much work on the main thread or waiting for a lock on it, so the Android can't start our service at all.
