### ISSUE TITLE
Firebase messaging on iOS not working after updating hypertrack to 1.0.0

### ISSUE THREAD

**Issue by kmvignesh** [hypertrack/sdk-flutter#32]
We have integrated following plugin to our app
```
hypertrack_plugin: 0.4.3
firebase_messaging: ^14.2.1
```
It was working pretty good. While migrating to latest flutter version we update `hypertrack_plugin` to `1.0.0`. Now our app is not receiving silent notification on iOS. In android its working fine.

So i downgraded `hypertrack_plugin` back to `0.4.3`. In this version its working fine. Please fix this notification issue on `hypertrack_plugin:1.0.0`

**Comment by kmvignesh** [comment]
Android crash log
```
E/AndroidRuntime(21167): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.ActivityRecognitionClient, but class was expected (declaration of 'com.google.android.gms.location.ActivityRecognitionClient' appears in /data/app/~~IIRhcSWSjZnpIqndbOeIWA==/com.***.***-CxC5PvJnfkZo7z8JOxUbIw==/base.apk!classes8.dex)
E/AndroidRuntime(21167): 	at com.hypertrack.sdk.activity.ActivityProvider.subscribe(ActivityProvider.kt:59)
E/AndroidRuntime(21167): 	at com.hypertrack.sdk.core.Core$handleAction$1.invokeSuspend(Core.kt:166)
E/AndroidRuntime(21167): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(21167): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(21167): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/AndroidRuntime(21167): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/AndroidRuntime(21167): 	at java.lang.Thread.run(Thread.java:1012)
E/AndroidRuntime(21167): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@70245cd, java.util.concurrent.Executors$FinalizableDelegatedExecutorService@6ca5e82]
```

**Comment by pavel-kuznetsov-hypertrack** [comment]
https://hypertrack.com/docs/android-sdk-faq#how-to-fix-device-not-getting-any-location-events-and-not-showing-any-outages
